name: Pylint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint:
    uses: validityBase/vbase-github-actions/.github/workflows/python-lint.yml@v1
    with:
      runner: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
      python-version: "3.12"
      requirements-files: |
        requirements/dev.txt
      pylint-command: pylint --fail-under=8.0 $(git ls-files '*.py')
